2017-01-20 04:02:06,209 [Thread-4:123145369120768] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-01-20 04:03:13,034 [Thread-10:123145360707584] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/company/staff/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1657, in changelist_view
    selection_note=_('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such column: company_staff.organization_id
<<<<<<< HEAD
2017-01-21 23:07:14,000 [Thread-3:10988] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
=======
2017-01-22 01:44:47,085 [Thread-4:123145546571776] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-01-22 03:21:32,220 [Thread-4:123145492606976] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/company/staff/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1657, in changelist_view
    selection_note=_('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such column: company_staff.organization_id
2017-01-22 03:23:41,433 [Thread-10:123145517383680] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/company/staff/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1657, in changelist_view
    selection_note=_('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such column: company_staff.organization_id
2017-01-22 03:25:08,991 [Thread-15:123145402777600] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/company/staff/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1450, in changeform_view
    self.save_related(request, form, formsets, not add)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1029, in save_related
    form.save_m2m()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/forms/models.py", line 436, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1573, in save_form_data
    getattr(instance, self.attname).set(data)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 938, in set
    old_ids = set(self.using(db).values_list(self.target_field.target_field.attname, flat=True))
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 155, in __iter__
    for row in compiler.results_iter():
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 789, in results_iter
    results = self.execute_sql(MULTI)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: company_staff_skills
2017-01-22 05:53:21,827 [Thread-4:123145419739136] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-01-22 05:59:56,775 [Thread-40:123145502937088] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/company/staff/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1007, in save_model
    obj.save()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table company_staff has no column named department_id
2017-01-22 06:02:37,485 [Thread-2:123145368866816] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/company/staff/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1007, in save_model
    obj.save()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table company_staff has no column named department_id
2017-01-22 06:02:49,246 [Thread-7:123145368866816] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/company/staff/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1007, in save_model
    obj.save()
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: table company_staff has no column named department_id
2017-01-22 06:07:27,924 [Thread-59:123145519624192] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/Users/user/workspace/Python/web/dssms/project/models.py", line 37, in __unicode__
    return type(pro_actors)
NameError: global name 'pro_actors' is not defined
2017-01-22 06:09:01,913 [Thread-15:123145399349248] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
TypeError: coercing to Unicode: need string or buffer, type found
2017-01-22 06:10:33,039 [Thread-7:123145370931200] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found
2017-01-22 06:11:31,664 [Thread-6:123145543966720] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found
2017-01-22 06:12:21,403 [Thread-6:123145459478528] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/Users/user/workspace/Python/web/dssms/project/models.py", line 37, in __unicode__
    print type(self.pro_actors__set)
AttributeError: 'Actor' object has no attribute 'pro_actors__set'
2017-01-22 06:15:48,290 [Thread-4:123145394262016] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/Users/user/workspace/Python/web/dssms/project/models.py", line 37, in __unicode__
    print type(self.pro_actors_set.all())
AttributeError: 'Actor' object has no attribute 'pro_actors_set'
2017-01-22 06:16:34,208 [Thread-5:123145393188864] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/Users/user/workspace/Python/web/dssms/project/models.py", line 37, in __unicode__
    print type(self.pro_actors_set.all())
AttributeError: 'Actor' object has no attribute 'pro_actors_set'
2017-01-22 06:16:43,689 [Thread-10:123145393188864] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/Users/user/workspace/Python/web/dssms/project/models.py", line 37, in __unicode__
    print type(self.pro_actors_set.all())
AttributeError: 'Actor' object has no attribute 'pro_actors_set'
2017-01-22 07:40:50,436 [Thread-6:123145436418048] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/Users/user/workspace/Python/web/dssms/project/models.py", line 38, in __unicode__
    for act in self.pro_actors_set.all():
AttributeError: 'Actor' object has no attribute 'pro_actors_set'
2017-01-22 07:41:32,811 [Thread-6:123145502982144] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/Users/user/workspace/Python/web/dssms/project/models.py", line 38, in __unicode__
    for act in self.pro_actors__set.all():
AttributeError: 'Actor' object has no attribute 'pro_actors__set'
2017-01-22 07:43:32,357 [Thread-6:123145469837312] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/Users/user/workspace/Python/web/dssms/project/models.py", line 38, in __unicode__
    for act in self.pro_actors.objects.all():
AttributeError: 'ManyRelatedManager' object has no attribute 'objects'
2017-01-22 07:43:55,252 [Thread-6:123145454530560] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/project/actor/add/
Traceback (most recent call last):
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1453, in changeform_view
    self.log_addition(request, new_object, change_message)
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 719, in log_addition
    object_repr=force_text(object),
  File "/Users/user/project_env/dssms_env/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/Users/user/workspace/Python/web/dssms/project/models.py", line 38, in __unicode__
    for act in self.pro_actors.object.all():
AttributeError: 'ManyRelatedManager' object has no attribute 'object'
>>>>>>> d783d9f3211d801aee306f9f629111dd57e49041
